# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='F', max_length=1)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.IntegerField(choices=[(0, 'Iniciado'), (1, 'Confirmado'), (2, 'Fechado'), (3, 'Enviado'), (4, 'Finalizado'), (5, 'Cancelado')], default=0)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fechado', models.DateField(blank=True, null=True)),
                ('data_enviado', models.DateField(blank=True, null=True)),
                ('data_finalizado', models.DateField(blank=True, null=True)),
                ('data_cancelado', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acrescimos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('saldo', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.Produto'),
        ),
    ]
